# TII-RATM dataset config — OpenVINS VIO + gate detections

/**:
  ros__parameters:
    odometry_topic: "/ov_msckf/odomimu"
    detections_topic: "/detections/gates"
    corrected_localization_topic: "slam/corrected_localization"
    corrected_path_topic: "slam/corrected_path"
    map_frame: "map"
    odom_frame: "odom"
    robot_frame: "base_link"
    viz_main_markers_topic: "slam_viz/markers/main"
    viz_temp_markers_topic: "slam_viz/markers/temp"
    main_graph_odometry_distance_threshold: 2.0
    main_graph_odometry_orientation_threshold: 1.0
    temp_graph_odometry_distance_threshold: 0.2
    temp_graph_odometry_orientation_threshold: 1.0
    odometry_is_relative: false
    generate_odom_map_transform: true
    earth_to_map:
      x: 0.003
      y: -1.505
      z: 0.070
      roll: 0.055326
      pitch: 0.149604
      yaw: -3.091816
    force_object_type: "aruco"
    fixed_objects:
      gate_1:
        type: "aruco"
        pose: [4.01, 1.31, 1.16, 0.0]
      gate_2:
        type: "aruco"
        pose: [3.97, -1.29, 1.17, 0.0]
      gate_3:
        type: "aruco"
        pose: [-3.94, -1.32, 1.17, 0.0]
      gate_4:
        type: "aruco"
        pose: [-3.98, 1.31, 1.14, 0.0]
